apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: gitlab-ce.westus3.cloudapp.azure.com:5050/gitlab-instance-501ed118/spring
        imagePullPolicy: Always
        ports:
        - name: spring-port
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWItY2Uud2VzdHVzMy5jbG91ZGFwcC5henVyZS5jb206NTA1MCI6IHsKCQkJImF1dGgiOiAiY205dmREcGhNVXhVUm1WR2NWTmlRbTl0V0ZoU1pFMUhSelZtUWs1c2JESjJRVkI1TXpKd1JVUkJWekJ2VDJOelBRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
