services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: "${GITLAB_FQDN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${GITLAB_FQDN}"
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    ports:
      - '80:80'
      - '443:443'
      - '1022:22'
      - '5050:5050'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
  runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'gitlab-runner-config:/etc/gitlab-runner'

volumes:
  gitlab-runner-config:
