- name: Install GitLab
  hosts: gitlabs
  remote_user: adminuser

  tasks:
    - name: Update system
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
    - name: Install PIP
      become: true
      ansible.builtin.apt:
        name:
          - python3-pip
    - name: Get Docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/docker-install.sh
        mode: "0700"
    - name: Execute Docker install script
      become: true
      ansible.builtin.command:
        cmd: /tmp/docker-install.sh
        creates: /usr/bin/docker
    - name: Add adminuser to docker group
      become: true
      ansible.builtin.user:
        user: adminuser
        append: true
        groups:
          - docker
    - name: Copy the GitLab docker-compose file
      ansible.builtin.copy:
        src: gitlab.docker-compose.yml
        dest: /tmp/docker-compose.yml
        mode: "0600"
    - name: Install PIP packages
      become: true
      ansible.builtin.pip:
        name:
          - docker
          - PyYAML
          - docker-compose
    - name: Run GitLab docker-compose
      become: true
      community.docker.docker_compose:
        project_src: /tmp/
      environment:
        GITLAB_FQDN: '{{ gitlab_fqdn }}'
        GITLAB_HOME: '/srv/gitlab'
    - name: Copy the GitLab Runner docker-compose file
      ansible.builtin.copy:
        src: gitlab-runner.docker-compose.yml
        dest: /tmp/docker-compose.yml
        mode: "0600"
    - name: Run GitLab Runner docker-compose
      become: true
      community.docker.docker_compose:
        project_src: /tmp/
    - name: Copy the GitLab Runner config.toml
      ansible.builtin.copy:
        src: gitlab-runner.config.toml
        dest: /tmp/config.toml
        mode: "0600"
    - name: Change the GitLab Runner options
      become: true
      community.docker.docker_container_copy_into:
        container: gitlab-runner
        path: /tmp/config.toml
        container_path: /etc/gitlab-runner/config.toml
    - name: Restart GitLab Runner
      become: true
      community.docker.docker_container:
        name: gitlab-runner
        restart: true
