concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "941b1068f69c"
  url = "https://gitlab-ce.westus3.cloudapp.azure.com/"
  id = 2
  token = "Ki3g_LDheFvQzRkx1Lsq"
  token_obtained_at = "2023-02-23T10:58:44Z"
  token_expires_at = "0001-01-01T00:00:00Z"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "ruby:2.7"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
