- name: Set hosts files for K8S cluster
  hosts: '{{ k8s_main_ip }},{{ k8s_worker_ip }}'
  remote_user: adminuser

  tasks:
    - name: Append main to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^k8s-main'
        line: 'k8s-main {{ k8s_main_ip }}'
    - name: Append worker to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^k8s-worker'
        line: 'k8s-worker {{ k8s_worker_ip }}'
